language: node_js
node_js:
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"
services:
  - mongodb
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
script: "npm run test"
install:
  - npm install
  - npm run bower
before_script: "npm run build"
